<%@ Page Title="Principal" Language="VB" MasterPageFile="~/MasterPage.master" AutoEventWireup="false" CodeFile="Default.aspx.vb" Inherits="_Default" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

    <div class="rellink noprint" style="font-style: italic; margin-bottom: 0.5em;">
    <h1>Cosmos:</h1>
    
    </div>

<p  style="margin: 0.5em 0px; padding: 20px;">
    &nbsp;<b>Cosmos</b>, en su sentido más general, es sinónimo de<span>&nbsp;</span><a href="https://es.wikipedia.org/wiki/Universo" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Universo">universo</a><span>&nbsp;</span>o<span>&nbsp;</span><a href="https://es.wikipedia.org/wiki/Mundo" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Mundo">mundo</a>, el conjunto de todo lo existente, aunque también es empleado para referirse exclusivamente al<span>&nbsp;</span><a href="https://es.wikipedia.org/wiki/Espacio_exterior" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Espacio exterior">espacio exterior</a><span>&nbsp;</span>a la<span>&nbsp;</span><a href="https://es.wikipedia.org/wiki/Tierra" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Tierra">Tierra</a>. El término cosmos además denota orden y organización, es el universo visto como un sistema ordenado o armonioso.</p>
<p style="margin: 0.5em 0px; padding: 20px;">
    Originalmente fue una palabra utilizada por los<span>&nbsp;</span><a class="mw-redirect" href="https://es.wikipedia.org/wiki/Antiguos_griegos" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Antiguos griegos">antiguos griegos</a><span>&nbsp;</span>para designar la totalidad de la existencia. Los griegos creían que el cosmos se regía por una serie de leyes («<i><a href="https://es.wikipedia.org/wiki/Nomos" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Nomos">nomos</a></i>»​), las cuales serían uno de los objetivos de comprensión de los primeros pensadores con los que se iniciaría entonces una versión embrionaria de la<span>&nbsp;</span><a href="https://es.wikipedia.org/wiki/Filosofía_griega" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Filosofía griega">filosofía griega</a>. Estas leyes, a su vez, se entendía que establecían un determinado orden («<i><a href="https://es.wikipedia.org/wiki/Dice" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Dice">diké</a></i>») 
    antítesis de<span>&nbsp;</span><a href="https://es.wikipedia.org/wiki/Caos" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Caos">caos</a>, caracterizado por el desequilibrio o desorden («<i><a href="https://es.wikipedia.org/wiki/Adicia" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Adicia">adikía</a></i>»). El<span>&nbsp;</span><a href="https://es.wikipedia.org/wiki/Tiempo" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Tiempo">tiempo</a><span>&nbsp;</span>en el cosmos no era concebido de forma lineal como lo es en la actualidad, sino de una forma cíclica: la periodicidad con la que se daban determinados<span>&nbsp;</span><a href="https://es.wikipedia.org/wiki/Meteorología" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Meteorología">fenómenos meteorológicos</a><span>&nbsp;</span>es ejemplo de ello (y entre otros). Conceptos como la nada, el no ser, el vacío, el infinito o lo 
    ilimitado no eran comprensibles en la época en que aparece el término: la<span>&nbsp;</span><a href="https://es.wikipedia.org/wiki/Civilización_minoica" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Civilización minoica">civilización minoica</a>, pues tampoco existían de facto. El estudio del cosmos, desde cualquier punto de vista, se llama<span>&nbsp;</span><a href="https://es.wikipedia.org/wiki/Cosmología" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Cosmología">cosmología</a>.</p>

</asp:Content>

