<%@ Page Title="Tierra" Language="VB" MasterPageFile="~/MasterPage.master" AutoEventWireup="false" CodeFile="Seccion1.aspx.vb" Inherits="Seccion1" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <p style="margin: 0.5em 0px; color: rgb(32, 33, 34); font-family: sans-serif; font-size: 24px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: bold; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
        La Tierra:</p>
<p style="margin: 0.5em 0px; padding: 20px; color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
        La<span>&nbsp;</span><b>Tierra</b><span>&nbsp;</span>(del<span>&nbsp;</span><a href="https://es.wikipedia.org/wiki/Latín" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Latín">latín</a><span>&nbsp;</span><i><a href="https://es.wikipedia.org/wiki/Tellus" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Tellus">Terra</a></i>,​<span>&nbsp;</span><a href="https://es.wikipedia.org/wiki/Mitología_romana" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Mitología romana">deidad romana</a><span>&nbsp;</span>equivalente a<span>&nbsp;</span><a href="https://es.wikipedia.org/wiki/Gea" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Gea">Gea</a>,<span>&nbsp;</span><a href="https://es.wikipedia.org/wiki/Mitología_griega" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Mitología griega">diosa 
        griega</a><span>&nbsp;</span>de la<span>&nbsp;</span><a href="https://es.wikipedia.org/wiki/Feminidad" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Feminidad">feminidad</a><span>&nbsp;</span>y la<span>&nbsp;</span><a href="https://es.wikipedia.org/wiki/Fecundidad" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Fecundidad">fecundidad</a>) es un<span>&nbsp;</span><a href="https://es.wikipedia.org/wiki/Planeta" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Planeta">planeta</a><span>&nbsp;</span>del<span>&nbsp;</span><a href="https://es.wikipedia.org/wiki/Sistema_solar" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Sistema solar">sistema solar</a><span>&nbsp;</span>que<span>&nbsp;</span><a href="https://es.wikipedia.org/wiki/Traslación_de_la_Tierra" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Traslación de la Tierra">gira</a><span>&nbsp;</span>alrededor de su<span>&nbsp;</span><a href="https://es.wikipedia.org/wiki/Estrella" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Estrella">estrella</a><span>&nbsp;</span>—el<span>&nbsp;</span><a href="https://es.wikipedia.org/wiki/Sol" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Sol">Sol</a>— 
        en la tercera<span>&nbsp;</span><a href="https://es.wikipedia.org/wiki/Órbita#%C3%93rbitas_planetarias" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Órbita">órbita</a><span>&nbsp;</span>más interna. Es el más denso y el quinto mayor de los ocho planetas del sistema solar. También es el mayor de los cuatro<span>&nbsp;</span><a href="https://es.wikipedia.org/wiki/Planeta_terrestre" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Planeta terrestre">terrestres</a><span>&nbsp;</span>o rocosos.</p>
    <p style="margin: 0.5em 0px; padding: 20px; color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
        La Tierra se formó hace aproximadamente 4550 millones de años y la<span>&nbsp;</span><a href="https://es.wikipedia.org/wiki/Abiogénesis" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Abiogénesis">vida surgió</a><span>&nbsp;</span>unos mil millones de años después. Es el hogar de millones de<span>&nbsp;</span><a class="mw-redirect" href="https://es.wikipedia.org/wiki/Especies" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Especies">especies</a>, incluidos los<span>&nbsp;</span><a href="https://es.wikipedia.org/wiki/Homo_sapiens" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Homo sapiens">seres 
        humanos</a><span>&nbsp;</span>y actualmente el único<span>&nbsp;</span><a class="mw-redirect" href="https://es.wikipedia.org/wiki/Cuerpo_astronómico" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Cuerpo astronómico">cuerpo astronómico</a><span>&nbsp;</span>donde se conoce la existencia de<span>&nbsp;</span><a href="https://es.wikipedia.org/wiki/Vida" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Vida">vida</a>.​ La<span>&nbsp;</span><a href="https://es.wikipedia.org/wiki/Atmósfera_terrestre" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Atmósfera terrestre">atmósfera</a><span>&nbsp;</span>y 
        otras condiciones<span>&nbsp;</span><a class="mw-redirect" href="https://es.wikipedia.org/wiki/Abiótico" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Abiótico">abióticas</a><span>&nbsp;</span>han sido alteradas significativamente por la<span>&nbsp;</span><a class="mw-redirect" href="https://es.wikipedia.org/wiki/Biosfera" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Biosfera">biosfera</a><span>&nbsp;</span>del planeta, favoreciendo la proliferación de<span>&nbsp;</span><a class="mw-redirect" href="https://es.wikipedia.org/wiki/Organismos_aerobios" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Organismos aerobios">organismos aerobios</a>, así como la formación de una<span>&nbsp;</span><a href="https://es.wikipedia.org/wiki/Capa_de_ozono" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Capa de ozono">capa de ozono</a><span>&nbsp;</span>que junto con el<span>&nbsp;</span><a href="https://es.wikipedia.org/wiki/Campo_magnético_terrestre" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Campo magnético terrestre">campo 
        magnético terrestre</a><span>&nbsp;</span>bloquean la<span>&nbsp;</span><a href="https://es.wikipedia.org/wiki/Radiación_ultravioleta" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Radiación ultravioleta">radiación solar dañina</a>, permitiendo así la vida en la Tierra.​ Las<span>&nbsp;</span><a href="https://es.wikipedia.org/wiki/Geofísica" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Geofísica">propiedades físicas de la Tierra</a>, la historia<span>&nbsp;</span><a href="https://es.wikipedia.org/wiki/Geología" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Geología">geológica</a><span>&nbsp;</span>y 
        su órbita han permitido que la vida siga existiendo. Se estima que el planeta seguirá siendo capaz de sustentar vida durante otros 500 millones de años, ya que según las previsiones actuales, pasado ese tiempo la creciente luminosidad del Sol terminará causando la extinción de la biosfera.</p>
</asp:Content>

